# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
