# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='defencive_array_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('offensive', 'OFFENSIVE'), ('defensive', 'DEFENSIVE')], max_length=20),
        ),
    ]
