# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20170716_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('offensive', 'OFFENSIVE'), ('defensive', 'DEFENSIVE'), ('', '')], max_length=20),
        ),
    ]
