# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20170716_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='player',
            name='attacking_no',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
