# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20170720_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='game_id',
            new_name='player_id',
        ),
    ]
