# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20170720_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='refree',
            name='winners',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('offencive', 'OFFENcIVE'), ('defencive', 'DEFENcIVE'), ('', '')], max_length=20),
        ),
    ]
