# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20170721_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('offensive', 'OFFENsIVE'), ('defensive', 'DEFENsIVE'), ('', '')], max_length=20),
        ),
    ]
